FROM python:3.7

WORKDIR /src

COPY pyproject.toml poetry.lock ./

RUN pip install pip --upgrade && \
    pip install poetry==1.0.2 && \
    poetry config virtualenvs.create false --local && \
    poetry install --no-interaction --no-dev

RUN useradd app

COPY . .

CMD celery -A project worker -l info --concurrency=10
